In [1]:
import pandas as pd

In [4]:
items= pd.read_csv('items.csv')
orders= pd.read_csv('orders.csv')

In [ ]:
items

,id,order_id,name,is_veg
0,1,127143465064,Paratha Kuruma,1
1,2,127143465064,Gobi Manchurian Dry,1
2,3,127077028490,Amritsari Paneer Tikka Lasagne,1
3,4,126888939416,Eggless Red Velvet Jar,1
4,5,125668909627,SEV PURI,1
...,...,...,...,...
188,189,1129725726,Triple Choco Chip Thick Shake,1
189,190,1123341565,Cookie and Cream Milkshake,1
190,191,1123287736,Veg Pulao + 3 Phulkas + Dal Fry + Mango Drink ...,1
191,192,1096353194,Cheese Tandoori Veg Pizza Sandwich,1
192,193,1096353194,Mixed Choco Sandwich,1

In [6]:
items['name']

0                                         Paratha Kuruma
1                                    Gobi Manchurian Dry
2                         Amritsari Paneer Tikka Lasagne
3                                 Eggless Red Velvet Jar
4                                               SEV PURI
                             ...
188                        Triple Choco Chip Thick Shake
189                           Cookie and Cream Milkshake
190    Veg Pulao + 3 Phulkas + Dal Fry + Mango Drink ...
191                   Cheese Tandoori Veg Pizza Sandwich
192                                 Mixed Choco Sandwich
Name: name, Length: 193, dtype: object

In [7]:
items['name'].unique

<bound method Series.unique of 0                                         Paratha Kuruma
1                                    Gobi Manchurian Dry
2                         Amritsari Paneer Tikka Lasagne
3                                 Eggless Red Velvet Jar
4                                               SEV PURI
                             ...
188                        Triple Choco Chip Thick Shake
189                           Cookie and Cream Milkshake
190    Veg Pulao + 3 Phulkas + Dal Fry + Mango Drink ...
191                   Cheese Tandoori Veg Pizza Sandwich
192                                 Mixed Choco Sandwich
Name: name, Length: 193, dtype: object>

In [8]:
items['name'].unique()

array(['Paratha Kuruma', 'Gobi Manchurian Dry',
       'Amritsari Paneer Tikka Lasagne', 'Eggless Red Velvet Jar',
       'SEV PURI', 'MASALA PURI', 'Sepangkizhangu Fries', 'Masala Kulcha',
       'Onion Aloo Mixed Paratha', 'Mixed Vegetable Raita',
       'Penne Arrabiata Pasta La Vista',
       'Pind Di Daal Makhani with Jeera Rice', 'Alfredo',
       'North Indian Value Combo Meals', 'Veg Zinger',
       'Burnt Garlic Noodles + Chilli Corn (Serves 1)',
       'Chicken Fried Rice + Bbq Shredded Chicken Sauce',
       'Burnt Garlic Chicken Rice + Chilly Shredded Chicken (Serves 1)',
       'Butter Chicken', 'Naan', 'Seven Taste Uttapam', 'Phulka',
       'Kadai Paneer', 'Ghee Paneer Masal Dosa', 'Sambar Idli',
       'Pomegranate Juices', 'Mango Mastani',
       'Paneer Tikka Sub ( 15 cm, 6 Inch )',
       'Corn & Peas Sub ( 15 cm, 6 Inch )', 'Classic Mac & Cheese',
       'Awadhi Paneer with Matar Pulao', 'Sprite Can (300 ml)',
       'Nawabi Paneer Lababdar Parotta Bowl',
       'Triple Ripple Death by Chocolate',
       'Paneer 65 with Chilli Garlic Fried Rice',
       'Baked Veggie Pizza Wrap', 'Jumbo Paneer Chole Wrap',
       'Rajma Masala Rice Bowl (Mini)',
       'Paneer Signature Rice Bowl (Mini)', 'Hazelnut Brownie',
       'American Cheese Supreme - Veg', 'Mcflurry Oreo Small',
       'Snack box', 'McSpicy Paneer Burger', 'Fries (R)',
       'New Chocolate Chip Muffin', 'Palak Paneer Jumbo Lunchbox',
       'Palak Paneer Bread Kulcha Lunchbox', 'Red Velvet Lava Cake',
       'Aloo Paratha With Dal Makhani', 'Brownie', 'Baby Corn Manchurian',
       'Aloo Sakh with Poori (3 Nos)',
       'Side Dish with Phulka Chapati (2 Nos)', 'Gobi 65',
       'Cheese Corn Nuggets', 'Veg Nuggets',
       'Butter Masala Corn Sandwich', 'Super Saver Paneer Rice Bowl Meal',
       'Triple Chocolate Waffle', 'Brownie Hotfudge Ice Cream Jar',
       'BBQ Cottage Sauce Pizza', 'Corn & Cheddar Quesadilla',
       'Garlic Bread With Cheese', 'Oreo Brownie',
       'Trio of Chocolate Jar', 'Gobi Manchurian', 'Cashew Pulao',
       'Paneer Pulao', 'Butter Naan + Paneer Butter Masala + RoseMilk',
       'Gobi 65 Dry', 'Nawabi Paneer Lababdar with Matar Pulao',
       'Double Chocolate Mousse',
       'Everyday Value 2 Reg Classic Paneer Combo', 'Cheesy Jalapeno Dip',
       'Chicken Schezwan Fried Rice', 'Paneer & Onion', 'Chicken Parcel',
       'Chicken Sausage', 'Capsicum', 'Golden Corn', 'Farmhouse',
       'Desi Dal Tadka with Jeera Rice',
       'Paneer Butter Masala with Mattar Pulao',
       'Mutter Paneer & Paratha Lunchbox', 'Strawberry (Baby)',
       'Hazelnut (Baby)', 'Curd Rice', 'Chocolate Milk Shake',
       'Garlic  Naan', 'Butter Naan', 'Gobi Masala',
       'Strawberry Milk Shake', "Good ol' Rajma Chawal",
       'Peri Peri Chicken with Egg Corn Rice',
       'The Paneer Overload Fusion Box', 'Kitkat Oreo Shake [300 ml]',
       'Paneer Butter Masala with Matar Pulao + Choice of Dessert',
       'Oreo Chocolate Melt Jar', 'Classic Mac & Cheese ',
       "Bailey's Chocolate Mousse",
       'Chocolate Hazelnut Hunger Shake (Regular)',
       'Makai Masala Rice Bowl', 'Brownie Surprise',
       'Corn & Peas Sub (15 cms, 6 Inch)',
       'Paneer Tikka Sub (15 cms, 6 Inch)', 'Chocolate Lovers',
       'Swiss Choco Brownie', 'Paneer Biryani',
       'Berry Blast Shake [300 ml]', 'Paneer & corn Pasta',
       'Paneer Pulao with Kadhi', 'Tawa Ghee Phulka', 'Mattar Paneer',
       'Punjabi Chaach Di-Bottle (Butter Milk)', 'Cheese Garlic Kulcha',
       'Belgian Chocolate - Dark', 'Peas Pulao ', 'Mixed Veg Raita',
       'Paneer Tikka Masala', 'Roti', 'Cookies & Cream',
       'Cheese corn Wrap', 'Butterscotch Ice cream',
       'Swiss Chocolate Ice cream', 'Oreo Cream and Fudge',
       'Gobi Manchurian (Dry)', 'Paneer Fried Rice', 'Chicken Fried Rice',
       'Dragon Chicken', 'Classic Corn (Personal)', 'Garlic Breadsticks',
       'Punjabi Thali (Limited)', 'Fajita Veggies Quesadilla',
       'Cheesy Double Decker Taco Veg', 'Chocodilla', 'Trimasu Shake',
       'Phulka Chapati', 'Daily Special Side Dish (Portion)',
       'Idli (2 Pcs)', 'Chapathi Korma', 'Paneer Pulao with Raita',
       'Poori Masala', 'Uttapam', 'Crunchy Chicken',
       'Mango Blast Thick Shake', 'Cheesy Rice Bowl - Veg',
       'Mexican McAlooTikki Burger         \t', 'McEgg Meal ( R )\t',
       'Veg Pulao with Raita', 'Rasmalai', 'Tawa Paneer Frankie',
       'Schezwan Paneer Frankie', 'Mexican Fries (Chef Suggested)',
       'Maggi Italiano', 'Bubble Gum Ice cream (95 gms)',
       'Butterscotch Bliss Ice cream (95 gms)', 'Cheesy Dip',
       'Butterscotch Mousse Cake', 'Triple Choco Chip Thick Shake',
       'Cookie and Cream Milkshake',
       'Veg Pulao + 3 Phulkas + Dal Fry + Mango Drink (200 ml)',
       'Cheese Tandoori Veg Pizza Sandwich', 'Mixed Choco Sandwich'],
      dtype=object)

In [9]:
items['name'].nunique()

164

In [12]:
items.groupby('is_veg')['name'].count()

is_veg
0     12
1    180
2      1
Name: name, dtype: int64

In [13]:
grouped = items.groupby('is_veg')['name']

for is_veg, names_group in grouped:
    print(f"Vegetarian: {is_veg}")
    print(names_group)

Vegetarian: 0
16       Chicken Fried Rice + Bbq Shredded Chicken Sauce
17     Burnt Garlic Chicken Rice + Chilly Shredded Ch...
18                                        Butter Chicken
43                                             Snack box
82                           Chicken Schezwan Fried Rice
84                                        Chicken Parcel
85                                       Chicken Sausage
105                 Peri Peri Chicken with Egg Corn Rice
148                                   Chicken Fried Rice
149                                       Dragon Chicken
170                                      Crunchy Chicken
175                                   McEgg Meal ( R )\t
Name: name, dtype: object
Vegetarian: 1
0                                         Paratha Kuruma
1                                    Gobi Manchurian Dry
2                         Amritsari Paneer Tikka Lasagne
3                                 Eggless Red Velvet Jar
4                                               SEV PURI
                             ...
188                        Triple Choco Chip Thick Shake
189                           Cookie and Cream Milkshake
190    Veg Pulao + 3 Phulkas + Dal Fry + Mango Drink ...
191                   Cheese Tandoori Veg Pizza Sandwich
192                                 Mixed Choco Sandwich
Name: name, Length: 180, dtype: object
Vegetarian: 2
67    Oreo Brownie
Name: name, dtype: object

In [18]:
items['chickenfound']=items['name'].str.find('Chicken')
items[items['chickenfound']!=-1]

,id,order_id,name,is_veg,chickenfound
16,17,118594611361,Chicken Fried Rice + Bbq Shredded Chicken Sauce,0,0
17,18,118594611361,Burnt Garlic Chicken Rice + Chilly Shredded Ch...,0,13
18,19,118594611361,Butter Chicken,0,7
82,83,86796819721,Chicken Schezwan Fried Rice,0,0
84,85,86796243798,Chicken Parcel,0,0
85,86,86796243798,Chicken Sausage,0,0
105,106,63528835993,Peri Peri Chicken with Egg Corn Rice,0,10
148,149,43875533945,Chicken Fried Rice,0,0
149,150,43875533945,Dragon Chicken,0,7
170,171,20698577867,Crunchy Chicken,0,8

In [21]:
itemnew =items.groupby('name')['id'].count().reset_index()

In [25]:
itemnew.sort_values(by=['id'],ascending=False)

                                          name  id
46                        Classic Mac & Cheese   4
114     Paneer Butter Masala with Mattar Pulao   3
31                            Cheese corn Wrap   3
110                        Paneer & corn Pasta   3
70                             Gobi Manchurian   3
..                                         ...  ..
56              Desi Dal Tadka with Jeera Rice   1
57                     Double Chocolate Mousse   1
58                              Dragon Chicken   1
60   Everyday Value 2 Reg Classic Paneer Combo   1
163                                 Veg Zinger   1

[164 rows x 2 columns]

In [26]:
orders

,id,order_id,order_total,restaurant_name,order_time,rain_mode,on_time
0,1,127143465064,463.0,A2B Veg,2022-02-05 19:07:45,0,1
1,2,127077028490,252.0,Firangi Bake,2022-02-05 00:40:28,0,1
2,3,126888939416,190.0,The Table,2022-02-02 20:25:40,0,1
3,4,125668909627,258.0,Sree gupta bhavan,2022-01-19 17:31:50,0,0
4,5,125301846779,194.0,Idlies,2022-01-15 11:34:07,0,1
...,...,...,...,...,...,...,...
90,91,1161151700,313.0,Domino's Pizza,2018-04-06 19:05:59,0,0
91,92,1129725726,192.0,The Thick Shake Factory,2018-01-07 17:12:33,0,1
92,93,1123341565,125.0,Food Centralis,2017-12-10 20:51:31,0,1
93,94,1123287736,209.0,Rice n Spice,2017-12-10 19:24:06,0,0
94,95,1096353194,140.0,The Sandwich Shop,2017-07-02 19:09:02,0,0

In [27]:
orders['order_id'].nunique()

95

In [28]:
orders['restaurant_name'].unique()

array(['A2B Veg', 'Firangi Bake', 'The Table', 'Sree gupta bhavan',
       'Idlies', "Shyam's Bombay Halwa House", 'The Bowl Company',
       'Super Munch', "Mansukh's Sweets and Snacks", 'KFC',
       'The Chopstix- Kk Nagar', 'Sabarees Veg Restaurant', 'Lassi House',
       'Subway', 'Faasos', "McDonald's", 'LunchBox', 'Drunken Monkey',
       "Sangeetha's Desi Mane", 'The Sandwich Shop 2.0',
       'The Belgian Waffle Co.', 'The Thickshake Factory',
       "Amelie's Cafe & Creamery", 'Kamakshi Mess',
       'Bakya Veg Restaurant', 'Roll Over', "Domino's Pizza",
       'Moonlight Takeaway & Delivery', 'Richy Rich Ice Creams',
       'HOTEL ANANDHA BHAVAN (Imperial Road)', 'VEJ', 'Frozen Bottle',
       'Good For One', 'KEVENTERS', 'The Good Bowl', 'Cream and Fudge',
       'Food Track', 'The Belgian Waffle Co', 'Oh so Stoned', 'Pizza Hut',
       "Desi Rasoi's Punjabi Dhaba", 'Taco Bell', 'Tibbs Frankie',
       'Maggevala Curly Cravings', 'Ibaco', 'The Thick Shake Factory',
       'Food Centralis', 'Rice n Spice', 'The Sandwich Shop'],
      dtype=object)

In [32]:
ordernew = orders.groupby('restaurant_name')['order_id'].nunique()
ordernew

restaurant_name
A2B Veg                                  4
Amelie's Cafe & Creamery                 1
Bakya Veg Restaurant                     1
Cream and Fudge                          2
Desi Rasoi's Punjabi Dhaba               1
Domino's Pizza                           4
Drunken Monkey                           1
Faasos                                   2
Firangi Bake                             1
Food Centralis                           1
Food Track                               5
Frozen Bottle                            2
Good For One                             1
HOTEL ANANDHA BHAVAN (Imperial Road)     2
Ibaco                                    1
Idlies                                   1
KEVENTERS                                1
KFC                                      1
Kamakshi Mess                            1
Lassi House                              1
LunchBox                                 2
Maggevala Curly Cravings                 1
Mansukh's Sweets and Snacks              6
McDonald's                               2
Moonlight Takeaway & Delivery            2
Oh so Stoned                             1
Pizza Hut                                1
Rice n Spice                             1
Richy Rich Ice Creams                    1
Roll Over                                2
Sabarees Veg Restaurant                  1
Sangeetha's Desi Mane                    4
Shyam's Bombay Halwa House               2
Sree gupta bhavan                        2
Subway                                   2
Super Munch                              1
Taco Bell                                2
The Belgian Waffle Co                    1
The Belgian Waffle Co.                   2
The Bowl Company                        12
The Chopstix- Kk Nagar                   1
The Good Bowl                            1
The Sandwich Shop                        1
The Sandwich Shop 2.0                    1
The Table                                4
The Thick Shake Factory                  1
The Thickshake Factory                   2
Tibbs Frankie                            1
VEJ                                      1
Name: order_id, dtype: int64

In [39]:
ordernew = orders.groupby('restaurant_name')['order_id'].nunique()
ordernew = orders.groupby('restaurant_name')['order_id'].nunique().reset_index()
ordernew

                         restaurant_name  order_id
0                                A2B Veg         4
1               Amelie's Cafe & Creamery         1
2                   Bakya Veg Restaurant         1
3                        Cream and Fudge         2
4             Desi Rasoi's Punjabi Dhaba         1
5                         Domino's Pizza         4
6                         Drunken Monkey         1
7                                 Faasos         2
8                           Firangi Bake         1
9                         Food Centralis         1
10                            Food Track         5
11                         Frozen Bottle         2
12                          Good For One         1
13  HOTEL ANANDHA BHAVAN (Imperial Road)         2
14                                 Ibaco         1
15                                Idlies         1
16                             KEVENTERS         1
17                                   KFC         1
18                         Kamakshi Mess         1
19                           Lassi House         1
20                              LunchBox         2
21              Maggevala Curly Cravings         1
22           Mansukh's Sweets and Snacks         6
23                            McDonald's         2
24         Moonlight Takeaway & Delivery         2
25                          Oh so Stoned         1
26                             Pizza Hut         1
27                          Rice n Spice         1
28                 Richy Rich Ice Creams         1
29                             Roll Over         2
30               Sabarees Veg Restaurant         1
31                 Sangeetha's Desi Mane         4
32            Shyam's Bombay Halwa House         2
33                     Sree gupta bhavan         2
34                                Subway         2
35                           Super Munch         1
36                             Taco Bell         2
37                 The Belgian Waffle Co         1
38                The Belgian Waffle Co.         2
39                      The Bowl Company        12
40                The Chopstix- Kk Nagar         1
41                         The Good Bowl         1
42                     The Sandwich Shop         1
43                 The Sandwich Shop 2.0         1
44                             The Table         4
45               The Thick Shake Factory         1
46                The Thickshake Factory         2
47                         Tibbs Frankie         1
48                                   VEJ         1

In [44]:
ordernew = orders.groupby('restaurant_name')['order_id'].nunique().reset_index()

ordernew['Rank']=ordernew['order_id'].rank(method='first', ascending=False)
ordernew.sort_values(by=['order_id'],ascending=False)

                         restaurant_name  order_id  Rank
39                      The Bowl Company        12   1.0
22           Mansukh's Sweets and Snacks         6   2.0
10                            Food Track         5   3.0
0                                A2B Veg         4   4.0
44                             The Table         4   7.0
5                         Domino's Pizza         4   5.0
31                 Sangeetha's Desi Mane         4   6.0
20                              LunchBox         2  12.0
46                The Thickshake Factory         2  21.0
38                The Belgian Waffle Co.         2  20.0
36                             Taco Bell         2  19.0
34                                Subway         2  18.0
33                     Sree gupta bhavan         2  17.0
32            Shyam's Bombay Halwa House         2  16.0
29                             Roll Over         2  15.0
23                            McDonald's         2  13.0
24         Moonlight Takeaway & Delivery         2  14.0
11                         Frozen Bottle         2  10.0
7                                 Faasos         2   9.0
3                        Cream and Fudge         2   8.0
13  HOTEL ANANDHA BHAVAN (Imperial Road)         2  11.0
17                                   KFC         1  32.0
40                The Chopstix- Kk Nagar         1  43.0
37                 The Belgian Waffle Co         1  42.0
6                         Drunken Monkey         1  25.0
4             Desi Rasoi's Punjabi Dhaba         1  24.0
41                         The Good Bowl         1  44.0
8                           Firangi Bake         1  26.0
42                     The Sandwich Shop         1  45.0
43                 The Sandwich Shop 2.0         1  46.0
45               The Thick Shake Factory         1  47.0
2                   Bakya Veg Restaurant         1  23.0
47                         Tibbs Frankie         1  48.0
35                           Super Munch         1  41.0
9                         Food Centralis         1  27.0
18                         Kamakshi Mess         1  33.0
12                          Good For One         1  28.0
30               Sabarees Veg Restaurant         1  40.0
28                 Richy Rich Ice Creams         1  39.0
27                          Rice n Spice         1  38.0
26                             Pizza Hut         1  37.0
25                          Oh so Stoned         1  36.0
1               Amelie's Cafe & Creamery         1  22.0
14                                 Ibaco         1  29.0
15                                Idlies         1  30.0
21              Maggevala Curly Cravings         1  35.0
16                             KEVENTERS         1  31.0
19                           Lassi House         1  34.0
48                                   VEJ         1  49.0

In [42]:
ordernew['Rank']=ordernew['order_id'].rank(method='first', ascending=False)
ordernew[ordernew['Rank']==1]
ordernew.sort_values(by=['order_id'],ascending=False)

                         restaurant_name  order_id  Rank
39                      The Bowl Company        12   1.0
22           Mansukh's Sweets and Snacks         6   2.0
10                            Food Track         5   3.0
0                                A2B Veg         4   4.0
44                             The Table         4   7.0
5                         Domino's Pizza         4   5.0
31                 Sangeetha's Desi Mane         4   6.0
20                              LunchBox         2  12.0
46                The Thickshake Factory         2  21.0
38                The Belgian Waffle Co.         2  20.0
36                             Taco Bell         2  19.0
34                                Subway         2  18.0
33                     Sree gupta bhavan         2  17.0
32            Shyam's Bombay Halwa House         2  16.0
29                             Roll Over         2  15.0
23                            McDonald's         2  13.0
24         Moonlight Takeaway & Delivery         2  14.0
11                         Frozen Bottle         2  10.0
7                                 Faasos         2   9.0
3                        Cream and Fudge         2   8.0
13  HOTEL ANANDHA BHAVAN (Imperial Road)         2  11.0
17                                   KFC         1  32.0
40                The Chopstix- Kk Nagar         1  43.0
37                 The Belgian Waffle Co         1  42.0
6                         Drunken Monkey         1  25.0
4             Desi Rasoi's Punjabi Dhaba         1  24.0
41                         The Good Bowl         1  44.0
8                           Firangi Bake         1  26.0
42                     The Sandwich Shop         1  45.0
43                 The Sandwich Shop 2.0         1  46.0
45               The Thick Shake Factory         1  47.0
2                   Bakya Veg Restaurant         1  23.0
47                         Tibbs Frankie         1  48.0
35                           Super Munch         1  41.0
9                         Food Centralis         1  27.0
18                         Kamakshi Mess         1  33.0
12                          Good For One         1  28.0
30               Sabarees Veg Restaurant         1  40.0
28                 Richy Rich Ice Creams         1  39.0
27                          Rice n Spice         1  38.0
26                             Pizza Hut         1  37.0
25                          Oh so Stoned         1  36.0
1               Amelie's Cafe & Creamery         1  22.0
14                                 Ibaco         1  29.0
15                                Idlies         1  30.0
21              Maggevala Curly Cravings         1  35.0
16                             KEVENTERS         1  31.0
19                           Lassi House         1  34.0
48                                   VEJ         1  49.0

In [45]:
orders

,id,order_id,order_total,restaurant_name,order_time,rain_mode,on_time
0,1,127143465064,463.0,A2B Veg,2022-02-05 19:07:45,0,1
1,2,127077028490,252.0,Firangi Bake,2022-02-05 00:40:28,0,1
2,3,126888939416,190.0,The Table,2022-02-02 20:25:40,0,1
3,4,125668909627,258.0,Sree gupta bhavan,2022-01-19 17:31:50,0,0
4,5,125301846779,194.0,Idlies,2022-01-15 11:34:07,0,1
...,...,...,...,...,...,...,...
90,91,1161151700,313.0,Domino's Pizza,2018-04-06 19:05:59,0,0
91,92,1129725726,192.0,The Thick Shake Factory,2018-01-07 17:12:33,0,1
92,93,1123341565,125.0,Food Centralis,2017-12-10 20:51:31,0,1
93,94,1123287736,209.0,Rice n Spice,2017-12-10 19:24:06,0,0
94,95,1096353194,140.0,The Sandwich Shop,2017-07-02 19:09:02,0,0

In [48]:
 orders['order_time']=orders['order_time'].apply(pd.to_datetime)
 orders['Year']=orders['order_time'].dt.year
 orders

,id,order_id,order_total,restaurant_name,order_time,rain_mode,on_time,Year
0,1,127143465064,463.0,A2B Veg,2022-02-05 19:07:45,0,1,2022
1,2,127077028490,252.0,Firangi Bake,2022-02-05 00:40:28,0,1,2022
2,3,126888939416,190.0,The Table,2022-02-02 20:25:40,0,1,2022
3,4,125668909627,258.0,Sree gupta bhavan,2022-01-19 17:31:50,0,0,2022
4,5,125301846779,194.0,Idlies,2022-01-15 11:34:07,0,1,2022
...,...,...,...,...,...,...,...,...
90,91,1161151700,313.0,Domino's Pizza,2018-04-06 19:05:59,0,0,2018
91,92,1129725726,192.0,The Thick Shake Factory,2018-01-07 17:12:33,0,1,2018
92,93,1123341565,125.0,Food Centralis,2017-12-10 20:51:31,0,1,2017
93,94,1123287736,209.0,Rice n Spice,2017-12-10 19:24:06,0,0,2017
94,95,1096353194,140.0,The Sandwich Shop,2017-07-02 19:09:02,0,0,2017

In [49]:
orders2=orders.groupby('Year')['order_total'].sum().reset_index()
orders2

   Year  order_total
0  2017        474.0
1  2018       3436.0
2  2019       7484.0
3  2020       3442.0
4  2021      11343.0
5  2022       1677.0

In [53]:

orders2['previoussales']=orders2['order_total'].shift(1)
orders2['%diff']=(orders2['order_total']-orders2['previoussales'])/orders2['previoussales']
orders2

   Year  order_total  previoussales     %diff
0  2017        474.0            NaN       NaN
1  2018       3436.0          474.0  6.248945
2  2019       7484.0         3436.0  1.178114
3  2020       3442.0         7484.0 -0.540086
4  2021      11343.0         3442.0  2.295468
5  2022       1677.0        11343.0 -0.852156